### ISSUE TITLE
what is this modules status?

### ISSUE THREAD

**Issue by maxlath** [richorama/level-geospatial#3]
hello, it seems that project hasn't been much active those last few years, would you still be interested in merging PRs such as #2? 

In the eventuality that you are not interested in continuing to maintain this module, do you think you could transfer ownership to the [Level](https://github.com/Level) organization? cc @vweevers

thanks in advance!

**Comment by vweevers** [comment]
We can't move every module to Level, there's not enough time & active contributors. Although Level has no official rules about which modules "qualify", I would say this does not, because:

1. It's not widely depended upon
2. It's a relatively specific use case, not something that all level databases can potentially benefit from.

**Comment by richorama** [comment]
'dormant' is the status. It didn't gain much interest, so it didn't get much investment.
